### ISSUE TITLE
STATUS: of an install on Mark II, pi4B

### ISSUE THREAD

**Issue by Olzeke51** [OpenVoiceOS/ovos-installer#74]
http://sprunge.us/XGWLHi  for the ovos-installer.log
also did http://sprunge.us/Exwe7n
per the failed output message - via ssh
![Failed-Screenshot_2024-04-19_20-25-08](https://github.com/OpenVoiceOS/ovos-installer/assets/25271367/4aec2a48-0950-44e7-bdc8-6c480714e0ca)
that is a copy of the final message
Gary Olzeke51
'
I do believe that @goldyfruit is the one that wants this ??? others are okay

**Comment by goldyfruit** [comment]
According to the logs, you have a network connectivity issue. Does the Mark II is close to the WiFi access point?!

**Comment by Olzeke51** [comment]
I use a network cable, assumed that over-rode the wifi/bluetooth.
I'll have to find a way to disable it....
Thanks
been slow to responds - work , debugging the logs, trying diff shutdowns on
the Mark2 recommended

**Comment by goldyfruit** [comment]
Gonna close for now, please feel free to re-open if needed. :+1:

**Comment by denics** [comment]
perhaps the issue is with the wifi timeout because of the power management default in the raspberry? adding this:
```
tasks:
    - name: Wifi Power Management | Disable wifi power management
      ansible.builtin.cron:
        name: "Disable power management"
        special_time: reboot
        job: "/usr/sbin/iwconfig wlan0 power off"
        user: root
```
disable power management on boot
